name: Control de Calidad - NestJS Backend (pnpm)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env: # la etiqueta env se usa cuando se definen variables que estas utilizando en tu codigo, a diferencia del with que se usa cuando estas usando variables que no estan corriendo en mi codigo
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PORT: ${{ vars.DB_PORT }}
  DB_USERNAME: ${{ vars.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ vars.DB_NAME }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRES_IN: '2h'
  BCRYPT_SALT_ROUNDS: 10
  PORT: 3005

jobs:
  control-calidad:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: teslo_shop_test
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Copiando el codigo del repositiro
        uses: actions/checkout@v4

      - name: Habilitando pnpm via Corepack
        run: |
            corepack enable
            corepack prepare pnpm@latest --activate

      - name: Instalando Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Instalando librerias con pnpm
        run: pnpm install --frozen-lockfile

      - name: Verificando codigo con ESLint
        run: pnpm run lint

      - name: Copilando el proyecto (Nest Build)
        run: pnpm run build

      - name: Ejecutando pruebas unitarias
        run: pnpm run test

      - name: Ejecutando pruebas e2e
        run: pnpm run test:e2e
