name: Control de Calidad - NestJS Backend (pnpm)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  control-calidad:
    runs-on: ubuntu-latest

    steps:
      - name: Copiando el codigo del repositorio
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Instalando pnpm
        run: npm install -g pnpm

      - name: Instalando librerias con pnpm
        run: pnpm install --frozen-lockfile

      - name: Verificando codigo con ESLint
        run: pnpm lint

      - name: Compilando el proyecto (Nest Build)
        run: pnpm build

      - name: Ejecutando pruebas unitarias
        run: pnpm test

      - name: Ejecutando pruebas e2e
        run: pnpm test:e2e
